In [191]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import classification_report


# ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [192]:
# Load the data
df = pd.read_csv('../models/df_clean.csv')

In [193]:
df.columns # check columns name

Index(['age', 'bmi', 'menstrual_regularity', 'hirsutism', 'acne_severity',
       'family_history_of_pcos', 'insulin_resistance', 'lifestyle_score',
       'stress_levels', 'socioeconomic_status', 'fertility_concerns',
       'undiagnosed_pcos_likelihood', 'diagnosis', 'urban_rural',
       'ethnicity_African', 'ethnicity_Asian', 'ethnicity_Caucasian',
       'ethnicity_Hispanic', 'ethnicity_Other'],
      dtype='str')

In [194]:
# check missing values
df.isnull().sum()

age                                0
bmi                                0
menstrual_regularity               0
hirsutism                          0
acne_severity                  60085
family_history_of_pcos             0
insulin_resistance                 0
lifestyle_score                    0
stress_levels                      0
socioeconomic_status               0
fertility_concerns                 0
undiagnosed_pcos_likelihood        0
diagnosis                          0
urban_rural                        0
ethnicity_African                  0
ethnicity_Asian                    0
ethnicity_Caucasian                0
ethnicity_Hispanic                 0
ethnicity_Other                    0
dtype: int64

In [195]:
df["acne_severity"] = df["acne_severity"].fillna(df["acne_severity"].median())

In [196]:
df.isnull().sum()

age                            0
bmi                            0
menstrual_regularity           0
hirsutism                      0
acne_severity                  0
family_history_of_pcos         0
insulin_resistance             0
lifestyle_score                0
stress_levels                  0
socioeconomic_status           0
fertility_concerns             0
undiagnosed_pcos_likelihood    0
diagnosis                      0
urban_rural                    0
ethnicity_African              0
ethnicity_Asian                0
ethnicity_Caucasian            0
ethnicity_Hispanic             0
ethnicity_Other                0
dtype: int64

### Train_test_split

In [197]:
# Train /test/validation split
from sklearn.model_selection import train_test_split
df_full_train , df_test = train_test_split(df, test_size = 0.2, 
                                           random_state = 11, stratify=df["diagnosis"])
df_train, df_val = train_test_split(df_full_train, test_size=0.25, 
                                    random_state =11,stratify=df_full_train["diagnosis"])

In [198]:
df_train

,age,bmi,menstrual_regularity,hirsutism,acne_severity,family_history_of_pcos,insulin_resistance,lifestyle_score,stress_levels,socioeconomic_status,fertility_concerns,undiagnosed_pcos_likelihood,diagnosis,urban_rural,ethnicity_African,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Other
119080,42,2,0,0,1.0,1,1,9,1,2,0,0.244082,0,1,0,0,1,0,0
39890,30,4,0,0,2.0,0,1,4,2,3,0,0.226364,0,0,1,0,0,0,0
47398,41,2,0,1,1.0,0,0,7,2,2,0,0.056051,0,1,0,1,0,0,0
1145,29,3,0,0,1.0,0,1,10,2,3,1,0.075634,0,1,0,0,0,1,0
115553,43,3,0,0,1.0,0,0,1,1,3,1,0.163251,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114038,29,3,0,0,1.0,0,0,5,3,2,0,0.092608,0,1,0,0,0,1,0
19454,43,2,0,0,2.0,0,0,10,1,1,0,0.087120,0,0,0,0,0,1,0
24618,19,2,0,0,1.0,1,0,2,3,1,1,0.174401,1,1,1,0,0,0,0
105936,21,2,0,0,1.0,0,0,7,3,2,1,0.124253,0,1,0,0,0,1,0
68779,21,4,0,0,1.0,1,0,10,2,2,1,0.092860,0,0,1,0,0,0,0

In [199]:
df_train = df_train.reset_index(drop =True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [200]:
df_test

,age,bmi,menstrual_regularity,hirsutism,acne_severity,family_history_of_pcos,insulin_resistance,lifestyle_score,stress_levels,socioeconomic_status,fertility_concerns,undiagnosed_pcos_likelihood,diagnosis,urban_rural,ethnicity_African,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Other
0,15,3,1,0,1.0,0,1,8,1,3,0,0.214516,0,0,0,0,0,0,1
1,32,2,0,0,1.0,0,0,9,2,1,0,0.129868,0,0,0,0,0,1,0
2,25,3,0,0,1.0,1,1,10,2,3,0,0.180305,0,1,1,0,0,0,0
3,48,2,0,0,2.0,0,0,4,2,2,1,0.152399,0,1,0,0,1,0,0
4,25,1,1,0,1.0,0,0,2,1,3,1,0.139269,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23995,30,2,0,1,1.0,0,1,9,1,2,0,0.184174,0,1,0,1,0,0,0
23996,46,2,0,0,2.0,1,1,5,2,3,0,0.190239,0,1,0,0,0,0,1
23997,20,2,1,0,1.0,0,0,7,2,2,0,0.155377,0,1,1,0,0,0,0
23998,26,2,0,0,1.0,1,0,3,1,1,1,0.142358,1,1,0,0,0,0,1
23999,38,1,1,0,1.0,0,1,7,2,2,0,0.179547,0,1,0,1,0,0,0

In [201]:
len(df_train), len(df_val), len(df_test)

(72000, 24000, 24000)

In [202]:
print(df_train["diagnosis"].value_counts(normalize=True))
print(df_val["diagnosis"].value_counts(normalize=True))
print(df_test["diagnosis"].value_counts(normalize=True))

diagnosis
0    0.895042
1    0.104958
Name: proportion, dtype: float64
diagnosis
0    0.895042
1    0.104958
Name: proportion, dtype: float64
diagnosis
0    0.895042
1    0.104958
Name: proportion, dtype: float64

In [203]:
# Separate features 
X_train = df_train.drop('diagnosis', axis=1)
X_val= df_val.drop('diagnosis', axis=1)
X_test = df_test.drop('diagnosis', axis=1)

In [204]:
## Target Features
y_train = df_train['diagnosis']
y_val = df_val['diagnosis']
y_test = df_test['diagnosis']

In [205]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_val = le.transform(y_val)
y_test = le.transform(y_test)

print(le.classes_)

[0 1]

### Build a Baseline Model

In [206]:
dv = DictVectorizer(sparse = False)
X_train = dv.fit_transform(X_train.to_dict(orient='records'))
X_val = dv.transform(X_val.to_dict(orient='records'))
X_test = dv.transform(X_test.to_dict(orient='records'))

In [207]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [208]:
print(classification_report(y_val, model.predict(X_val)))

              precision    recall  f1-score   support

           0       0.90      1.00      0.94     21481
           1       0.00      0.00      0.00      2519

    accuracy                           0.90     24000
   macro avg       0.45      0.50      0.47     24000
weighted avg       0.80      0.90      0.85     24000

#### Add class weight= balanced

In [209]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [210]:
print(classification_report(y_val, model.predict(X_val)))

              precision    recall  f1-score   support

           0       0.90      0.50      0.64     21481
           1       0.11      0.50      0.17      2519

    accuracy                           0.50     24000
   macro avg       0.50      0.50      0.41     24000
weighted avg       0.81      0.50      0.59     24000

#### Apply SMOTE

In [211]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

In [212]:
print(classification_report(y_val, model.predict(X_val)))

              precision    recall  f1-score   support

           0       0.90      0.50      0.64     21481
           1       0.11      0.50      0.17      2519

    accuracy                           0.50     24000
   macro avg       0.50      0.50      0.41     24000
weighted avg       0.81      0.50      0.59     24000